services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    volumes:
      - ../source/api:/app

  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ../source/web:/app

  postgres-17:
    container_name: postgres-17
    image: bitnami/postgresql:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: projeto_integrador
    volumes:
      - /var/lib/postgresql/data
